web_scrap:
  page_number: 499

database:
  test_size: 0.3
  random_state: 44


make_model:
  iterations: [500, 1000]
  depth: [4, 6, 10]
  learning_rate: [0.01, 0.05, 0.1]
  l2_leaf_reg: [1, 3, 5]
  border_count: [32, 64, 128]
