name: AWS Deployment

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repro
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: install dependesi
        run: |
          pip install -r requirements.txt

      - name: Login to AWS
        run: |
          aws configure set aws_access_key_id ${{ secrets.ACCESS_KEY_2 }}
          aws configure set aws_secret_access_key ${{ secrets.SECRET_ACCESS_KEY_2 }}
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 563364226105.dkr.ecr.ap-south-1.amazonaws.com


# add nothgin





































# name: CI Pipeline

# on:
#   push:

# jobs:
#   build:
  
#     runs-on: ubuntu-latest
#     steps:

#       - name: checkout repro
#         uses: actions/checkout@v3

#       - name: setup python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.11'


#       - name: install dependes
#         run: |
#           pip install -r requirements.txt
#           pip install "dvc[s3]"

#       - name: AWS
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
#         run: |
#           dvc pull
# # final

   
